import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./comon/Header";
import Footer from "./comon/Footer";
import Mainlayout from "./mainlayout";
import { Componydata } from "./services/componyServises";
import { Category, Subcategory } from "./services/HomeService";
import ScrollToTop from "./comon/ScrollToTop";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Monsta Furiture Exclusive",
  description: "Generated by create next app",
};



export default async function RootLayout({ children }) {
   let category= await Category()
   let subcategory=await Subcategory()
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Mainlayout>

          <Header  category={category} subcategory={subcategory} />
          {children}
          <ScrollToTop/>
          <Footer />

        </Mainlayout>
      </body>
    </html>
  );
}
